import { Github, Twitter, Linkedin } from "lucide-react";
import React from "react";
export default function Footer() {
    return (React.createElement("footer", { className: "bg-gradient-to-r from-primary via-secondary to-accent text-white py-12" },
        React.createElement("div", { className: "container mx-auto px-6" },
            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8" },
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-2xl font-bold mb-4" }, "SDC Club"),
                    React.createElement("p", { className: "text-sm text-gray-300" }, "Empowering students to innovate, create, and collaborate in the world of technology.")),
                React.createElement("div", null,
                    React.createElement("h4", { className: "text-xl font-semibold mb-4" }, "Quick Links"),
                    React.createElement("ul", { className: "space-y-2" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "#welcome", className: "hover:text-accent-dark transition-colors duration-300" }, "Home")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#members", className: "hover:text-accent-dark transition-colors duration-300" }, "Members")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#events", className: "hover:text-accent-dark transition-colors duration-300" }, "Events")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "#contact", className: "hover:text-accent-dark transition-colors duration-300" }, "Contact")))),
                React.createElement("div", null,
                    React.createElement("h4", { className: "text-xl font-semibold mb-4" }, "Connect With Us"),
                    React.createElement("div", { className: "flex space-x-4" },
                        React.createElement("a", { href: "#", className: "hover:text-accent-dark transition-colors duration-300" },
                            React.createElement(Github, { className: "w-6 h-6" })),
                        React.createElement("a", { href: "#", className: "hover:text-accent-dark transition-colors duration-300" },
                            React.createElement(Twitter, { className: "w-6 h-6" })),
                        React.createElement("a", { href: "#", className: "hover:text-accent-dark transition-colors duration-300" },
                            React.createElement(Linkedin, { className: "w-6 h-6" }))))),
            React.createElement("div", { className: "mt-8 pt-8 border-t border-white/20 text-center" },
                React.createElement("p", { className: "text-sm text-gray-300" },
                    "\u00A9 ",
                    new Date().getFullYear(),
                    " SDC Club. All rights reserved.")))));
}
